name: 'get-pr-commits'
description: 'A GitHub Action that get commits in current pull request, ignoring GHA workflow files'
inputs:
  token:
    description: 'A token with access to your repository scoped in as a secret'
    required: true
outputs:
  commits:
    description: 'Commits in the PR, formatted as a JSON string'
  commit_words:
    description: 'Commits in the PR with most special characters removed, for use in grep commands'
runs:
  using: 'node20'
  main: 'dist/index.js'
